hangman_words = [
    "apple",
    "brave",
    "climate",
    "dragon",
    "elephant",
    "forest",
    "giraffe",
    "horizon",
    "island",
    "jungle",
    "kitchen",
    "lemon",
    "mountain",
    "night",
    "octopus",
    "penguin",
    "quartz",
    "rainbow",
    "starfish",
    "tiger",
    "umbrella",
    "vivid",
    "wizard",
    "xylophone",
    "yacht",
    "zebra",
    "ancient",
    "blizzard",
    "chimney",
    "dolphin",
    "eagle",
    "fountain",
    "hiking",
    "insect",
    "jigsaw",
    "koala",
    "leopard",
    "mystery",
    "neon",
    "orchestra",
    "parrot",
    "quasar",
    "rocket",
    "sunflower",
    "tornado",
    "unicorn",
    "volcano",
    "whisper",
    "xenon",
]

win_message = """\n                              _       _ 
 _   _  ___  _   _  __      _(_)_ __ | |
| | | |/ _ \| | | | \ \ /\ / / | '_ \| |
| |_| | (_) | |_| |  \ V  V /| | | | |_|
 \__, |\___/ \__,_|   \_/\_/ |_|_| |_(_)
 |___/                                  \n"""
