data = [
    {
        "name": "Instagram",
        "follower_count": 346,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 500,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Dwayne Johnson (The Rock)",
        "follower_count": 320,
        "description": "Actor and former professional wrestler",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 300,
        "description": "Reality TV star and entrepreneur",
        "country": "United States",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 380,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 250,
        "description": "Singer and actress",
        "country": "United States",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 260,
        "description": "Singer and actress",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 270,
        "description": "Reality TV star and entrepreneur",
        "country": "United States",
    },
    {
        "name": "Beyoncé",
        "follower_count": 240,
        "description": "Singer and actress",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 230,
        "description": "Singer",
        "country": "Canada",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 220,
        "description": "Singer and songwriter",
        "country": "United States",
    },
    {
        "name": "Neymar Jr.",
        "follower_count": 200,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "National Geographic",
        "follower_count": 180,
        "description": "Educational media organization",
        "country": "United States",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 170,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 160,
        "description": "Singer and actress",
        "country": "United States",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 150,
        "description": "Rapper and singer",
        "country": "Trinidad and Tobago",
    },
    {
        "name": "LeBron James",
        "follower_count": 140,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 130,
        "description": "Model and TV personality",
        "country": "United States",
    },
    {
        "name": "Cardi B",
        "follower_count": 120,
        "description": "Rapper and singer",
        "country": "United States",
    },
    {
        "name": "Shakira",
        "follower_count": 110,
        "description": "Singer",
        "country": "Colombia",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 100,
        "description": "Singer and actress",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 90,
        "description": "Singer and songwriter",
        "country": "United States",
    },
    {
        "name": "Ellen DeGeneres",
        "follower_count": 80,
        "description": "Comedian and TV host",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 70,
        "description": "Actress and singer",
        "country": "United States",
    },
    {
        "name": "Will Smith",
        "follower_count": 60,
        "description": "Actor and rapper",
        "country": "United States",
    },
    {
        "name": "Emma Watson",
        "follower_count": 50,
        "description": "Actress and activist",
        "country": "United Kingdom",
    },
    {
        "name": "Priyanka Chopra",
        "follower_count": 40,
        "description": "Actress and producer",
        "country": "India",
    },
    {
        "name": "Rihanna",
        "follower_count": 30,
        "description": "Singer and entrepreneur",
        "country": "Barbados",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 20,
        "description": "Singer and songwriter",
        "country": "United States",
    },
    {
        "name": "Drake",
        "follower_count": 10,
        "description": "Rapper and singer",
        "country": "Canada",
    },
]
